# Generated by Django 4.0.2 on 2022-02-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancer_order', 'Can Cancel Order')]},
        ),
    ]
